#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           intake_r,      tmotorVex393, openLoop)
#pragma config(Motor,  port2,           chassis_bl,    tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_3, 1000)
#pragma config(Motor,  port3,           chassis_br,    tmotorVex393HighSpeed, openLoop, reversed, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port4,           arm_rb,          tmotorVex393, openLoop)
#pragma config(Motor,  port5,           arm_lb,          tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port6,           chassis_fl,    tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port7,           chassis_fr,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           arm_rt,        tmotorVex393, openLoop)
#pragma config(Motor,  port9,           arm_lt,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          intake_l,      tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
 
int liftAvoidTip = 0;
int motorspeed_r;
int motorspeed_l;
 
task main()
{
    while(true){
        if(abs(vexRT[Ch2]) > 10){
            motor[chassis_fr] = motorspeed_r;
            motor[chassis_br] = motorspeed_r;
            }else{
            motor[chassis_fr] = 0;
            motor[chassis_br] = 0;
        }
        if(abs(vexRT[Ch3]) > 10){
            motor[chassis_fl] = motorspeed_l;
            motor[chassis_bl] = motorspeed_l;
            }else{
            motor[chassis_fl] = 0;
            motor[chassis_bl] = 0;
        }
 
        if(vexRT[Btn5D] == 1 && vexRT[Btn5U] == 0){
            motor[intake_l] = 127;
            motor[intake_r] = 127;
            }else if(vexRT[Btn5U] == 1 && vexRT[Btn5D] == 0){
            motor[intake_l] = -127;
            motor[intake_r] = -127;
            }else if (vexRT[Btn5D] == 1 && vexRT[Btn5U] == 1){
            motor[intake_l] = -127;
            motor[intake_r] = 0;
            }else{
            motor[intake_l] = 0;
            motor[intake_r] = 0;
        }
 
        if(vexRT[Btn6U] == 1){
            motor[arm_lb] = 127;
            motor[arm_lt] = 127;
            motor[arm_rb] = 127;
            motor[arm_rt] = 127;
            }else if(vexRT[Btn6D] == 1){
            motor[arm_lb] = -127;
            motor[arm_lt] = -127;
            motor[arm_rb] = -127;
            motor[arm_rt] = -127;
            }else{
            motor[arm_lb] = 0;
            motor[arm_lt] = 0;
            motor[arm_rb] = 0;
            motor[arm_rt] = 0;
        }
 
        if (vexRT[Btn7U] == 1 && liftAvoidTip == 0){
            liftAvoidTip = 1;
            }else if (vexRT[Btn7D] == 1 && liftAvoidTip == 1){
            liftAvoidTip = 0;
            }else{
        }
 
        if (liftAvoidTip == 1){
            if (vexRT[Ch2] > 0 && vexRT[Ch2] < 500){
                motorspeed_r = 50;
                }else if (vexRT[Ch2] < 0 && vexRT[Ch2] > -500){
                motorspeed_r = -50;
            }
 
 
            if (vexRT[Ch3] > 0 && vexRT[Ch3] < 500){
                motorspeed_l = 50;
                }else if (vexRT[Ch3] < 0 && vexRT[Ch3] > -500){
                motorspeed_l = -50;
            }
 
            }else if (liftAvoidTip == 0){
            motorspeed_r = vexRT[Ch2];
            motorspeed_l = vexRT[Ch3];
        }
    }
}
